### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by macsek1911** [surfnturf57/ESP8266-WeatherSensor-Webserver#1]
Hi!
I tried compiling your script but it gives me this error: http://pastebin.com/a9Y3yqcn
What can I do about this?

**Comment by internetofhomethings** [comment]
The sketch was compiled using Arduino IDE Version 1.6.1. While attempting to compile with 1.6.5, a a few incompatibilities with Version 1.6.5 were identified. These have been corrected with the revised files uploaded to the repository. 

In addition, the required library files were restructured along with update to the readme.md file to clarify exactly how to install this sketch and dependent libraries.

This should correct the errors you encountered while compiling the sketch.

**Comment by macsek1911** [comment]
Thank you!
